### ISSUE TITLE
Undefined name 'entries'...  Is this line unreachable?

### ISSUE THREAD

**Issue by cclauss** [IBM-Cloud/github-traffic-stats#3]
Left over from #2   Does the __return__ statement on line just above mean that the code on this line is unreachable?  __PyLint__ is pretty good at detecting these kind of problems.

[flake8](http://flake8.pycqa.org) testing of https://github.com/IBM-Cloud/github-traffic-stats on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./backend/ghstats.py:610:63: F821 undefined name 'entries'
    resp = make_response(render_template('list.html', entries=entries))
                                                              ^
1     F821 undefined name 'entries'
1
```

**Comment by data-henrik** [comment]
new code version
